
############################################
# HoloRouter / nginx variables
############################################

HOLROUTER_IP="10.10.1.10"
HOLROUTER_HOSTNAME="HOLOROUTER.DOMAIN.LOCAL"

NGINX_DIR="/etc/nginx"
CONF_DIR="/etc/nginx/conf.d"
SSL_DIR="/etc/nginx/ssl"
NGINX_CONF="/etc/nginx/nginx.conf"

DNS_RESOLVER="127.0.0.1"

############################################
# VCF Management Services
############################################

VC_MGMT="vc-mgmt-a.site-a.vcf.lab"
NSX_MGMT="nsx-mgmt-a.site-a.vcf.lab"
SDDC_MGR="sddc-mgr.site-a.vcf.lab"
VCF_INSTALLER="vcfinstaller-a.site-a.vcf.lab"
OPS="ops-a.site-a.vcf.lab"

############################################
# Workload Domain Services
############################################

VC_WLD01="vc-wld01-a.site-a.vcf.lab"
NSX_WLD01="nsx-wld01-a.site-a.vcf.lab"

############################################
# ESXi Hosts
############################################

ESX_01="esx-01a.site-a.vcf.lab"
ESX_02="esx-02a.site-a.vcf.lab"
ESX_03="esx-03a.site-a.vcf.lab"
ESX_04="esx-04a.site-a.vcf.lab"
ESX_05="esx-05a.site-a.vcf.lab"
ESX_06="esx-06a.site-a.vcf.lab"
ESX_07="esx-07a.site-a.vcf.lab"
